### ISSUE TITLE
the code doesnt work.

### ISSUE THREAD

**Issue by Wouze** [vietnguyen1991/Photomosaic-generator#4]
when i run the script with all the things hav e been done correctly(image_pool, input)
i get this error

Traceback (most recent call last):
  File "/Users/khe/Desktop/bots/img to img/img to img.py", line 46, in <module>
    main(opt)
  File "/Users/khe/Desktop/bots/img to img/img to img.py", line 38, in main
    distance_matrix = np.linalg.norm(partial_avg_color - avg_colors, axis=1)
ValueError: operands could not be broadcast together with shapes (3,) (0,) 

could anyone help me <3.

**Comment by Hellohi3654** [comment]
try a different input image and or a different image pool

**Comment by Hellohi3654** [comment]
other thing
make sure you have these requirements
Requirements:
python 3.6
cv2
numpy

**Comment by Wouze** [comment]
Thanks!
I acctually fixed it but I don't remmeber what I made wrong.

but while you are here, why not make the output image in a higher resulotion? maybe 4k or above, with any input image.
